name: Deploy db site to github pages
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdzenie poprawności
        uses: actions/checkout@v4.2.2
    

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesMGreene/gh-pages-deploy@v1.0.0