name: Build and Push Docker Images
on:
  push:
    branches:
      - main
      - env-qa
      - env-test

permissions:
  contents: read
  pages: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: self-hosted

    environment: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Print future .env file parameters
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env

      - name: Create .env file
        env: 
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          WEB_PORT: ${{ secrets.WEB_PORT }}
        run: |
          docker-compose -f docker-compose/docker-compose-remote.yml -p ${{ github.ref_name }} up --build -d
          